#!/bin/bash
ICON=$HOME/.config/i3/images/lock.png
TMPBG=/tmp/screen.png
RES=1920x1080
scrot /tmp/screen.png
convert $TMPBG -scale 35%x -scale 287% -brightness-contrast -5x-3 $TMPBG
# convert $TMPBG -blur 0xcc $TMPBG
convert $TMPBG $ICON -gravity center -composite -matte $TMPBG
i3lock -u -i $TMPBG



