#!/bin/sh

# current_branch=$(git branch --show-current 2>/dev/null)
# gitprompt=""
# if [ -z $current_branch ]; then
#   gitprompt=""
# else
#   gitprompt="%{$fg[red]%}[%{$fg[green]%}$current_branch%{$fg[red]%}]%{$reset_color%}"
# fi

PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "
