import = ["/home/nachiket/.config/alacritty/env.toml", "/home/nachiket/.config/alacritty/colors/gruvbox.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 7

[window]
opacity = 0.8
